# Full project: https://gitlab.com/pages/plain-html
pages:
  stage: deploy
  script:
    - mkdir public
    - cp *.js *.html *.md public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
